CREATE TABLE comments (
    `comment_id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
    `parent_id` BIGINT UNSIGNED NOT NULL,
    `uuid` VARCHAR(100) NOT NULL,
    `comment` VARCHAR(100),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `delete_flg` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (comment_id),
    FOREIGN KEY (parent_id) REFERENCES comments (comment_id)
    ON DELETE CASCADE
)ENGINE=InnoDB;
